name: CI

on:
  push:
    branches: ["master"]
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust-env
      - run: cargo clippy --release

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust-env
      - run: cargo fmt --check

  doctest:
    name: Doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/setup-rust-env"
      - run: cargo test --doc
